/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coding;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK 
 */
public class CashOrCheckLoanDeposite extends javax.swing.JFrame {

    /**
     * Creates new form CashOrCheckLoanDeposite
     */
    public CashOrCheckLoanDeposite() {
        initComponents();
        setLocationRelativeTo(null);
        try{
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date sdate=sdf.parse(sdf.format(new java.util.Date()));
                    cd .setDate(sdate);
                    cd.setSelectableDateRange(new java.util.Date(),new java.util.Date());
    }catch(Exception e){
       l1.setText("Problem in Date");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nn = new javax.swing.JButton();
        amo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        amou1 = new javax.swing.JTextField();
        c = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cd = new com.toedter.calendar.JDateChooser();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CASH/CHECK MODE LOAN DEPOSITE");
        setResizable(false);

        nn.setBackground(new java.awt.Color(255, 51, 51));
        nn.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        nn.setText("SAVE TRANSACTION");
        nn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nnMouseClicked(evt);
            }
        });
        nn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnActionPerformed(evt);
            }
        });

        amo.setBackground(new java.awt.Color(204, 255, 204));
        amo.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        amo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amoMouseClicked(evt);
            }
        });
        amo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amoActionPerformed(evt);
            }
        });
        amo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amoKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("*AMOUNT");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GENERATE DETAILS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lan.setBackground(new java.awt.Color(153, 255, 204));
        lan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lan.setForeground(new java.awt.Color(0, 0, 204));
        lan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lanMouseEntered(evt);
            }
        });
        lan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("*Loan Account Number :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DEPOSITE LOAN AMOUNT");

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("*REMAINING AMOUNT");

        amou1.setBackground(new java.awt.Color(204, 255, 204));
        amou1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        amou1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amou1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amou1MouseClicked(evt);
            }
        });
        amou1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amou1ActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHECK" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("*MODE:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("*DATE :");

        cd.setBackground(new java.awt.Color(204, 255, 204));
        cd.setForeground(new java.awt.Color(255, 51, 102));
        cd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 153, 153));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 153, 153));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lan, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amou1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(amo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(nn)
                            .addGap(14, 14, 14)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lan)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(amou1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnActionPerformed
if(!lan.getText().equals("")){
        if(!amo.getText().equals("")&&!amou1.getText().equals("")&&cd != null){
            int gg=JOptionPane.showConfirmDialog(this, "Deposite Money ? ", "Loan Amount Money Deposite Conformation ", JOptionPane.YES_NO_OPTION);
                        if(gg == JOptionPane.YES_OPTION){
                            
                    try{
                        database.loan.c.setAutoCommit(false);
                            String gu=lan.getText();
                            float d3=Float.parseFloat(amo.getText());
                            ResultSet rs = database.dbconnect.st.executeQuery("select total_amount from loan_accounts where loan_account_number ='"+gu+"' ");
                            if(rs.next()){
                            float d1=rs.getFloat(1);
                            if(d1 != 0){    
                                 d1=d1-d3;
                                int fff=database.loan.st.executeUpdate("update loan_accounts set total_amount = '"+d1+"'  where loan_account_number = '"+gu+"' ");
                                   
                                                    if(d1 >=0 ){
                                                                                        database.transaction.insertLoanTransaction.setLong(1, Long.parseLong(lan.getText()));
                                                                                        database.transaction.insertLoanTransaction.setString(2,"--------------");

                                                                                        java.sql.Date jsd=new java.sql.Date(cd.getDate().getTime());
                                                                                        database.transaction.insertLoanTransaction.setDate(3, jsd);

                                                                                        String mode=(String)c.getSelectedItem();
                                                                                        database.transaction.insertLoanTransaction.setString(4, mode);

                                                                                        database.transaction.insertLoanTransaction.setFloat(5, d3);
                                                                                        database.transaction.insertLoanTransaction.setFloat(6, d1);
                                                                                        
                                                                                        int bh=database.transaction.insertLoanTransaction.executeUpdate();

                                                                                               if(bh !=0){
                                                                                                       System.out.println("success !");
                                                                                               }
                                                                                               else
                                                                                                   System.out.println("Error !");
                                                            
                                                            l1.setText("**Money Deposited");
                                                            database.loan.c.commit();
                                                            }
                                                            else{
                                                            l1.setText("**Deposite Amount Exceded !");
                                                            database.loan.c.rollback();
                                                            }
                                                    }
                            
                         else{
                        l1.setForeground(java.awt.Color.RED);
                        l1.setText("ALL LOAN AMMOUNT ALLREADY DEPOSITED .");
                        l2.setForeground(java.awt.Color.RED);
                        l2.setText("ALL LOAN AMMOUNT ALLREADY DEPOSITED .");
                         }
                    }else
                        l1.setText("Problem with Loan Account Number !");
                    }catch(Exception e){
                        l1.setText(""+e);
                    }
                    }
        }else
            l1.setText("Fill up all the Details Correctly !");
}else
    l1.setText("Please provide the Loan Account Number First !");
    }//GEN-LAST:event_nnActionPerformed

    private void amoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        if(!lan.getText().equals("")){
         long LOAN_ACCOUNT_NUMBER =Long.parseLong(lan.getText());
         String gu=lan.getText();
            try {
                ResultSet rs= database.loan.st.executeQuery("select monthly_installment,total_amount from loan_accounts where loan_account_number ='"+gu+"' ");
                if(rs.next()){
                        float amount=Float.parseFloat(rs.getString(1));
                        float t_amount=Float.parseFloat(rs.getString(2));
                        amo.setText(String.valueOf(amount));
                        float ffff=t_amount-amount;
                        String dd=String.valueOf(ffff);
                        amou1.setText(dd);
                }
                else{
                    l1.setText("Please check Loan Account Number !!");
                }
            } catch (SQLException ex) {
                l1.setText("Error While Communicating To Database!");
            }
         
        }else
            l1.setText("Provide Loan Account Number First !");
        }catch(Exception e){
       l1.setText("Please Enter The Loan Account Number In Number Format!!");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanActionPerformed
try{
        if(!lan.getText().equals("")){
         long LOAN_ACCOUNT_NUMBER =Long.parseLong(lan.getText());
         String gu=lan.getText();
            try {
                ResultSet rs= database.loan.st.executeQuery("select monthly_installment from loan_accounts where loan_account_number ='"+gu+"' ");
                if(rs.next()){
                        float amount=Float.parseFloat(rs.getString(1));
                        amo.setText(String.valueOf(amount));
                }
                else{
                    l1.setText("Please check Loan Account Number !!");
                }
            } catch (SQLException ex) {
                l1.setText("Error While Communicating To Database!");
            }
         
        }else
            l1.setText("Provide Loan Account Number First !");
        }catch(Exception e){
       l1.setText("Please Enter The Loan Account Number In Number Format!!");
}
    }//GEN-LAST:event_lanActionPerformed

    private void amou1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amou1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amou1ActionPerformed

    private void amoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amoKeyReleased
        if(!amo.getText().equals("")){    
        try{
                                String gu=lan.getText();
                                float d3=Float.parseFloat(amo.getText());
                                ResultSet rs = database.dbconnect.st.executeQuery("select total_amount from loan_accounts where loan_account_number ='"+gu+"' ");
                                if(rs.next()){
                                float d1=rs.getFloat(1);
                                if(d1 != 0){    
                                     d1=d1-d3;
                                        if(d1>= 0){
                                        amou1.setText(String.valueOf(d1));
                                        }  
                                        else{
                                            amou1.setText("");
                                            l1.setForeground(java.awt.Color.RED);
                                            l1.setText("**Deposite Amount Exceeded !");
                                       }
                                     }
                                else{
                                    l2.setForeground(java.awt.Color.RED);
                                    l2.setText("ALL LOAN AMMOUNT ALLREADY DEPOSITED .");
                                }
                                }
            }catch(Exception e){
                                l2.setText("error "+e);
                                }
                            
        }else
            l1.setText("Please provide the Amount!");
    }//GEN-LAST:event_amoKeyReleased

    private void lanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanMouseClicked
        l1.setText(null);
        l2.setText(null);
    }//GEN-LAST:event_lanMouseClicked

    private void amoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amoMouseClicked
        l1.setText(null);
        l2.setText(null);
    }//GEN-LAST:event_amoMouseClicked

    private void amou1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amou1MouseClicked
        l1.setText(null);
        l2.setText(null);
    }//GEN-LAST:event_amou1MouseClicked

    private void lanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lanMouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void nnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nnMouseClicked
     
    }//GEN-LAST:event_nnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashOrCheckLoanDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashOrCheckLoanDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashOrCheckLoanDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashOrCheckLoanDeposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashOrCheckLoanDeposite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amo;
    private javax.swing.JTextField amou1;
    private javax.swing.JComboBox<String> c;
    private com.toedter.calendar.JDateChooser cd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField lan;
    private javax.swing.JButton nn;
    // End of variables declaration//GEN-END:variables
}
