/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coding;

import static database.transaction.insertTransaction;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK 
 */
public class Deposite extends javax.swing.JFrame {

    /**
     * Creates new form Deposite
     */
    public Deposite() {
        initComponents();
        this.setLocationRelativeTo(null);
       try{
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date sdate=sdf.parse(sdf.format(new java.util.Date()));
                    dofb .setDate(sdate);
                    dofb.setSelectableDateRange(new java.util.Date(),new java.util.Date());
    }catch(Exception e){
       jjjj.setText("Problem in Date");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adhr = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        bal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        amou = new javax.swing.JTextField();
        fff = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        phnum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dofb = new com.toedter.calendar.JDateChooser();
        jjjj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposite Money");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MONEY DEPOSITE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("*Desired Account Number :");

        acn.setBackground(new java.awt.Color(153, 255, 204));
        acn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        acn.setForeground(new java.awt.Color(0, 0, 204));
        acn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acnMouseClicked(evt);
            }
        });
        acn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GENERATE DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*DATE :");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("*AADHAR NUMBER :");

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("*CUSTOMER NAME :");

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("*PREVIOUS BALANCE :");

        jLabel7.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("*TRANSACTION MODE :");

        adhr.setBackground(new java.awt.Color(204, 255, 204));
        adhr.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        adhr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adhrMouseClicked(evt);
            }
        });

        na.setBackground(new java.awt.Color(204, 255, 204));
        na.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        na.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naMouseClicked(evt);
            }
        });
        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });

        bal.setBackground(new java.awt.Color(204, 255, 204));
        bal.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        bal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balMouseClicked(evt);
            }
        });
        bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AMOUNT");

        amou.setBackground(new java.awt.Color(204, 255, 204));
        amou.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        amou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amouMouseClicked(evt);
            }
        });
        amou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amouActionPerformed(evt);
            }
        });
        amou.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amouKeyReleased(evt);
            }
        });

        fff.setBackground(new java.awt.Color(204, 255, 204));
        fff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHECK" }));
        fff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fffMouseClicked(evt);
            }
        });
        fff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fffActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton2.setText("REFRESH FIELDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton3.setText("SAVE TRANSACTION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        phnum.setBackground(new java.awt.Color(204, 255, 204));
        phnum.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        phnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phnumMouseClicked(evt);
            }
        });
        phnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnumActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*MOBILE NUMBER");

        dofb.setBackground(new java.awt.Color(204, 255, 204));
        dofb.setForeground(new java.awt.Color(255, 51, 102));
        dofb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dofb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dofbMouseClicked(evt);
            }
        });

        jjjj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jjjj.setForeground(new java.awt.Color(51, 51, 51));
        jjjj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(fff, 0, 282, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(dofb, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(adhr, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(phnum)
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amou, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(94, 94, 94))))
            .addComponent(jjjj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bal, fff});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {amou, phnum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jjjj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dofb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adhr))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(na)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phnum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fff, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adhr, amou, bal, dofb, jLabel4, na, phnum});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed

    private void balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balActionPerformed

    private void fffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fffActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        long ACCU=Long.parseLong(acn.getText());
                if(ACCU !=0 ){
                    
                        if(!acn.equals("")&&dofb != null&&!adhr.equals("")&&!na.equals("")&&!bal.equals("")&&!phnum.equals("")){
                            
                                String guu=amou.getText();
                                    try{
                                        if(!guu.equals("")){
                                                 long xy = Long.parseLong(guu);
                                                 if(xy != 0){
                                                        int ko=JOptionPane.showConfirmDialog(this, "Deposite Money ?", "Deposite Conformation !", JOptionPane.YES_NO_OPTION);
                                                            if(ko==JOptionPane.YES_OPTION){
                                                                    ResultSet rvs = database.dbconnect.st.executeQuery("select BALANCE from  customer_accounts where ACCOUNT_NUMBER = '"+ACCU+"' ");
                                                                        if(rvs.next()){

                                                                            long xc=rvs.getLong(1);
                                                                            long cv=xc+xy;

                                                                            int bbb=database.dbconnect.st.executeUpdate("update customer_accounts set BALANCE = '"+cv+"'  where ACCOUNT_NUMBER = '"+ACCU+"' ");
                                                                            
                                                                            database.transaction.insertTransaction.setLong(1, ACCU);
                                                                            database.transaction.insertTransaction.setString(2, na.getText());
                                                                                    
                                                                            java.sql.Date jsd=new java.sql.Date(dofb.getDate().getTime());
                                                                            database.transaction.insertTransaction.setDate(3, jsd);
                                                                            
                                                                            database.transaction.insertTransaction.setString(4, "Deposite");
                                                                                    
                                                                            String mode=(String)fff.getSelectedItem();
                                                                            database.transaction.insertTransaction.setString(5, mode);
                                                                            
                                                                            database.transaction.insertTransaction.setLong(6, xy);
                                                                            database.transaction.insertTransaction.setLong(7, xc);
                                                                            database.transaction.insertTransaction.setLong(8, cv);
                                                                            
                                                                            int bh=database.transaction.insertTransaction.executeUpdate();
                                                                            
                                                                            if(bh !=0){
                                                                                    System.out.println("success !");
                                                                            }
                                                                            else
                                                                                System.out.println("Error !");
                                                                                 jjjj.setText("* Successfully Money Deposited !");
                                                                            
                                                                               if(bbb != 0 ){
                                                                                   
                                                                                    amou.setText("");
                                                                            }
                                                                    }
                                                        }
                                                 }else
                                                     jjjj.setText("* Please Enter The Valid Amount !");

                                            }
                                             else
                                                 jjjj.setText("* Please Enter the Ammount to be Deposited.  ");
                                        }
                                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e);
                              }
                        }
                        else
                            jjjj.setText("* Please Enter All The Details Correctly !"); 
                
                }else
                {
                            jjjj.setText("* Please Enter The Valid Account Number !"); 
                }
    }
    catch(Exception e){
        jjjj.setText("* Please Enter The Valid Account Number !");
    }
                
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!acn.getText().equals("")){
            
        try{
                long ACCU=Long.parseLong(acn.getText());
                database.dbconnect.getUser.setLong(1, ACCU);
                ResultSet rs=database.dbconnect.getUser.executeQuery();
                 
                if(rs.next()){
                        
                    na.setText(rs.getString(3));
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date sdate=sdf.parse(sdf.format(new java.util.Date()));
                    dofb .setDate(sdate);
                    phnum.setText(rs.getString(5));
                    adhr.setText(rs.getString(10));
                    bal.setText(rs.getString(15));
                    
                    amou.requestFocusInWindow();
                }else{
                     jjjj.setText("* Please Check the Account number !");
                }
        }catch(Exception e){
                   jjjj.setText("* Please Enter the Account Number In Number Format !");
        }
        }
        else{
                    jjjj.setText("* Please Enter the Account number !");
                    acn.requestFocusInWindow();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        acn.setText("");
        dofb.setDate(null);
        adhr.setText("");
        na.setText("");
        bal.setText("");
        phnum.setText("");
        amou.setText("");
        jjjj.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnumActionPerformed

    private void amouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amouActionPerformed
         try{
        long ACCU=Long.parseLong(acn.getText());
                if(ACCU !=0 ){
                    
                        if(!acn.equals("")&&dofb != null&&!adhr.equals("")&&!na.equals("")&&!bal.equals("")&&!phnum.equals("")){
                            
                                String guu=amou.getText();
                                    try{
                                        if(!guu.equals("")){
                                                 long xy = Long.parseLong(guu);
                                                 if(xy != 0){
                                                        int ko=JOptionPane.showConfirmDialog(this, "Deposite Money ?", "Deposite Conformation !", JOptionPane.YES_NO_OPTION);
                                                            if(ko==JOptionPane.YES_OPTION){
                                                                    ResultSet rvs = database.dbconnect.st.executeQuery("select BALANCE from  customer_accounts where ACCOUNT_NUMBER = '"+ACCU+"' ");
                                                                        if(rvs.next()){

                                                                            long xc=rvs.getLong(1);
                                                                            long cv=xc+xy;

                                                                            int bbb=database.dbconnect.st.executeUpdate("update customer_accounts set BALANCE = '"+cv+"'  where ACCOUNT_NUMBER = '"+ACCU+"' ");
                                                                            
                                                                            database.transaction.insertTransaction.setLong(1, ACCU);
                                                                            database.transaction.insertTransaction.setString(2, na.getText());
                                                                                    
                                                                            java.sql.Date jsd=new java.sql.Date(dofb.getDate().getTime());
                                                                            database.transaction.insertTransaction.setDate(3, jsd);
                                                                            
                                                                            database.transaction.insertTransaction.setString(4, "Deposite");
                                                                                    
                                                                            String mode=(String)fff.getSelectedItem();
                                                                            database.transaction.insertTransaction.setString(5, mode);
                                                                            
                                                                            database.transaction.insertTransaction.setLong(6, xy);
                                                                            database.transaction.insertTransaction.setLong(7, xc);
                                                                            database.transaction.insertTransaction.setLong(8, cv);
                                                                            int bh=database.transaction.insertTransaction.executeUpdate();
                                                                            
                                                                            if(bh !=0){
                                                                                    System.out.println("success !");
                                                                            }
                                                                            else
                                                                                System.out.println("Error !");
                                                                                 jjjj.setText("* Successfully Money Deposited !");
                                                                            
                                                                               if(bbb != 0 ){
                                                                                   
                                                                                    amou.setText("");
                                                                            }
                                                                    }
                                                        }
                                                 }else
                                                     jjjj.setText("* Please Enter The Valid Amount !");

                                            }
                                             else
                                                 jjjj.setText("* Please Enter the Ammount to be Deposited.  ");
                                        }
                                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e);
                              }
                        }
                        else
                            jjjj.setText("* Please Enter All The Details Correctly !"); 
                
                }else
                {
                            jjjj.setText("* Please Enter The Valid Account Number !"); 
                }
    }
    catch(Exception e){
        jjjj.setText("* Please Enter The Valid Account Number !");
    }
                
   
    }//GEN-LAST:event_amouActionPerformed

    private void acnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnActionPerformed
        if(!acn.getText().equals("")){
            
        try{
                long ACCU=Long.parseLong(acn.getText());
                database.dbconnect.getUser.setLong(1, ACCU);
                ResultSet rs=database.dbconnect.getUser.executeQuery();
                 
                if(rs.next()){
                        
                    na.setText(rs.getString(3));
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date sdate=sdf.parse(sdf.format(new java.util.Date()));
                    dofb .setDate(sdate);
                    phnum.setText(rs.getString(5));
                    adhr.setText(rs.getString(10));
                    bal.setText(rs.getString(15));
                    
                    amou.requestFocusInWindow();
                }else{
                     jjjj.setText("* Please Check the Account number !");
                }
        }catch(Exception e){
                   jjjj.setText("* Please Enter the Account Number In Number Format !");
        }
        }
        else{
                    jjjj.setText("* Please Enter the Account number !");
                    acn.requestFocusInWindow();
        }
    }//GEN-LAST:event_acnActionPerformed

    private void amouKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amouKeyReleased
        try{
        long ACCU= Long.parseLong(acn.getText());
                if(ACCU !=0 ){
                    
                        if(!acn.equals("")&&dofb != null&&!adhr.equals("")&&!na.equals("")&&!bal.equals("")&&!phnum.equals("")){
                            
                                String guu=amou.getText();
                                    try{
                                        if(!guu.equals("")){
                                                 long xy = Long.parseLong(guu);
                                                 if(xy != 0){
                                                                    ResultSet rvs = database.dbconnect.st.executeQuery("select BALANCE from  customer_accounts where ACCOUNT_NUMBER = '"+ACCU+"' ");
                                                                        if(rvs.next()){

                                                                            long xc=rvs.getLong(1);
                                                                            long cv=xc+xy;
                                                                             jjjj.setText("* After TRansaction Your Bal Will Be : " + cv);

                                                                    }
                                                        
                                                 }else
                                                     jjjj.setText("* Please Enter The Valid Amount !");

                                            }
                                                else
                                                    jjjj.setText("* Please Enter the Ammount to be Deposited. ");
                                        }
                                        catch(Exception e){
                                    JOptionPane.showMessageDialog(null, e);
                              }
                        }
                        else
                            jjjj.setText("* Please Enter All The Details Correctly !"); 
                
                }else
                {
                            jjjj.setText("* Please Enter The Valid Account Number !"); 
                }
    }
    catch(Exception e){
        jjjj.setText("* Please Enter The Valid Account Number !");
    }
    }//GEN-LAST:event_amouKeyReleased

    private void acnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acnMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_acnMouseClicked

    private void phnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phnumMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_phnumMouseClicked

    private void amouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amouMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_amouMouseClicked

    private void balMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_balMouseClicked

    private void naMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_naMouseClicked

    private void adhrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adhrMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_adhrMouseClicked

    private void fffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fffMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_fffMouseClicked

    private void dofbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbMouseClicked
        jjjj.setText(null);
    }//GEN-LAST:event_dofbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acn;
    private javax.swing.JTextField adhr;
    private javax.swing.JTextField amou;
    private javax.swing.JTextField bal;
    private com.toedter.calendar.JDateChooser dofb;
    private javax.swing.JComboBox<String> fff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jjjj;
    private javax.swing.JTextField na;
    private javax.swing.JTextField phnum;
    // End of variables declaration//GEN-END:variables
}
