/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coding;

import static database.loan.insertLoanAccount;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK
 */
public class newLoanAccount extends javax.swing.JFrame {

    /**
     * Creates new form newLoanAccount
     */
    public newLoanAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date sdate;
        try {
            sdate = sdf.parse(sdf.format(new java.util.Date()));
            cd .setDate(sdate);
        } catch (ParseException ex) {
            Logger.getLogger(newLoanAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
        cd.setSelectableDateRange(new java.util.Date(),new java.util.Date());
        inter.setText("8");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bb = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        an = new javax.swing.JTextField();
        fmdl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        com = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        noi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        ta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mi = new javax.swing.JLabel();
        inter = new javax.swing.JLabel();
        cd = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW LOAN ACCOUNT");

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));

        bb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(0, 255, 51));
        bb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("*ACCOUNT NUMBER :");

        lan.setBackground(new java.awt.Color(204, 255, 204));
        lan.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        lan.setForeground(new java.awt.Color(255, 51, 102));
        lan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("*LOAN ACCOUNT NUMBER :");

        an.setBackground(new java.awt.Color(204, 255, 204));
        an.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        an.setForeground(new java.awt.Color(255, 51, 102));
        an.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anMouseClicked(evt);
            }
        });
        an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anActionPerformed(evt);
            }
        });

        fmdl.setBackground(new java.awt.Color(204, 255, 204));
        fmdl.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        fmdl.setForeground(new java.awt.Color(255, 51, 102));
        fmdl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fmdlMouseClicked(evt);
            }
        });
        fmdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmdlActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("*FMDL A/c NUMBER :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("*COMPANY:");

        com.setBackground(new java.awt.Color(204, 255, 204));
        com.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        com.setForeground(new java.awt.Color(255, 51, 102));
        com.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comMouseClicked(evt);
            }
        });
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("*SALARY :");

        sal.setBackground(new java.awt.Color(204, 255, 204));
        sal.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        sal.setForeground(new java.awt.Color(255, 51, 102));
        sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salMouseClicked(evt);
            }
        });
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("*LOAN TYPE :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("*DATE :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("*LOAN AMOUNT :");

        lam.setBackground(new java.awt.Color(204, 255, 204));
        lam.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        lam.setForeground(new java.awt.Color(255, 51, 102));
        lam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lamMouseClicked(evt);
            }
        });
        lam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("*RATE OF INTEREST :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("*NO OF INSTALLMENT :");

        noi.setBackground(new java.awt.Color(204, 255, 204));
        noi.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        noi.setForeground(new java.awt.Color(255, 51, 102));
        noi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noiMouseClicked(evt);
            }
        });
        noi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noiKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("*MONTHLY INSTALLMENT :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("*TOTAL AMOUNT :");

        type.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERSONAL", "EDUCATION", "HOME", "CAR", "BUSINESS", " " }));
        type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeMouseClicked(evt);
            }
        });

        ta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ta.setForeground(new java.awt.Color(51, 0, 0));
        ta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ta.setText("*******************");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("GRANT LOAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW LOAN ACCOUNT REGISTRATION");

        mi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mi.setForeground(new java.awt.Color(51, 0, 0));
        mi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mi.setText("*******************");

        inter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        inter.setForeground(new java.awt.Color(204, 255, 204));
        inter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inter.setText("*******************");
        inter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interKeyTyped(evt);
            }
        });

        cd.setBackground(new java.awt.Color(204, 255, 204));
        cd.setForeground(new java.awt.Color(255, 51, 102));
        cd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Check status");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Check status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 255));
        jButton4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton4.setText("REFRESH FIELDS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("GET LAN");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(com, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(fmdl, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(sal, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lan, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(an, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(type, 0, 268, Short.MAX_VALUE)
                                                .addComponent(cd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton4)
                                            .addComponent(lam, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inter, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(noi, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ta, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mi, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {an, com, fmdl, lam, lan, noi, sal, type});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel16)
                                                    .addComponent(lam, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(lan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(noi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(64, 64, 64)
                                                .addComponent(ta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fmdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel12)
                                        .addGap(25, 25, 25)))
                                .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {an, cd, com, fmdl, lam, lan, noi, sal, type});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anActionPerformed
        
       String s3= an.getText();
        if(!s3.equals("")){
                
            try {
                ResultSet rs=database.loan.st.executeQuery("select account_number from customer_accounts where account_number = '"+s3+"' ");
                    if(rs.next()){
                        long ACCOUNT_NUMBER = Long.parseLong(s3);
                        long vv=rs.getLong(1);
                        
                                if(vv == ACCOUNT_NUMBER){
                                    bb.setText("**"+ACCOUNT_NUMBER+" is Availabe !" );
                                }
                } else
                                     bb.setText("**"+s3+" is Unavailabe !");
            } catch (Exception ex) {
               bb.setText("**Error While Communicating To Database !");
            }
        }else{
            bb.setText("**Please provide the Account Number !");
            an.requestFocusInWindow();
        }
    }//GEN-LAST:event_anActionPerformed

    private void lanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanActionPerformed

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if((!an.getText().equals(""))){
            
            try{                                     
                                                        
                                                        
                                                        /*String s3=an.getText();
                                                        try {
                                                        ResultSet rs=database.loan.st.executeQuery("select fmdl_account_number from loan_accounts where fmdl_account_number = '"+s3+"' ");
                                                        if(rs.next()){
                                                        int cf = LOAN_ACCOUNT_NUMBER;
                                                        int vv=rs.getInt(1);
                                                        if(vv != cf){
                                                        bb.setText("**Everything all right");*/
                                                        if(!an.getText().equals("") && !lan.getText().equals("") &&  !fmdl.getText().equals("") &&  !sal.getText().equals("") 
                                                                    &&  !lam.getText().equals("") && !inter.getText().equals("") &&  !noi.getText().equals("") &&  !mi.getText().equals("")
                                                                    && !ta.getText().equals("") && cd != null && !com.getText().equals("") ){
                                                            
                                                                        long ACCOUNT_NUMBER = Long.parseLong(an.getText());
                                                                        long LOAN_ACCOUNT_NUMBER = Long.parseLong(lan.getText());
                                                                        long FMDL = Long.parseLong(fmdl.getText());
                                                                        long SALARY = Long.parseLong(sal.getText());
                                                                        float LOAN_AMOUNT = Float.parseFloat(lam.getText());
                                                                        float INTEREST = Float.parseFloat(inter.getText());
                                                                        int NUMBER_OF_INSTALLMENT = Integer.parseInt(noi.getText());
                                                                        float MONTHLY_INSTALMENT = Float.parseFloat(mi.getText());
                                                                        float TOTAL_AMOUNT = Float.parseFloat(ta.getText());
                                                                        java.util.Date DT=cd.getDate();
                                                                        String s1=com.getText();
                                                                        String s2=(String)type.getSelectedItem(); 
                                                            
                                                                    java.sql.Date SQL_DATE = new java.sql.Date(DT.getTime());
                                                                        try {
                                                                            database.loan.c.setAutoCommit(false);
                                                                            
                                                                            database.loan.insertLoanAccount.setLong(1, ACCOUNT_NUMBER);
                                                                            database.loan.insertLoanAccount.setLong(2, LOAN_ACCOUNT_NUMBER);
                                                                            database.loan.insertLoanAccount.setDate(3, SQL_DATE);
                                                                            database.loan.insertLoanAccount.setLong(4, FMDL);
                                                                            database.loan.insertLoanAccount.setString(5, s1);
                                                                            database.loan.insertLoanAccount.setLong(6, SALARY);
                                                                            database.loan.insertLoanAccount.setString(7, s2);
                                                                            database.loan.insertLoanAccount.setFloat(8, LOAN_AMOUNT);
                                                                            database.loan.insertLoanAccount.setFloat(9, INTEREST);
                                                                            database.loan.insertLoanAccount.setInt(10, NUMBER_OF_INSTALLMENT);
                                                                            database.loan.insertLoanAccount.setFloat(11, MONTHLY_INSTALMENT);
                                                                            database.loan.insertLoanAccount.setFloat(12, TOTAL_AMOUNT);
                                                                            
                                                                            int v=database.loan.insertLoanAccount.executeUpdate();
                                                                            
                                                                            String s3=an.getText();
                                                                            ResultSet rs=database.loan.st.executeQuery("select ACCOUNT_NUMBER from customer_accounts where ACCOUNT_NUMBER = '"+s3+"' ");
                                                                            if(rs.next()){
                                                                                //bb.setText("**Account is present !");
                                                                                    String s5=fmdl.getText();
                                                                                    ResultSet qs=database.loan.st.executeQuery("select ACCOUNT_NUMBER from customer_accounts where ACCOUNT_NUMBER = '"+s5+"' ");
                                                                                    if(qs.next()){
                                                                                        //bb.setText("**FMDL Account is present !");
                                                                                                if(v !=0){
                                                                                                        JOptionPane.showMessageDialog(null, "Loan Account has been CREATED with Loan Account Number : "+LOAN_ACCOUNT_NUMBER);
                                                                                                        database.loan.c.commit();
                                                                                                        dispose();
                                                                                                }
                                                                                                else{
                                                                                                        database.loan.c.rollback();
                                                                                                        bb.setText("**Error in Loan ACCOUNT CREATION !  Try With Another Loan Account Number .");
                                                                                                }
                                                                                    }else
                                                                                        bb.setText("**Invalid FMDL Account Number!");
                                                                                        database.loan.c.rollback();
                                                                                
                                                                            }else
                                                                                bb.setText("**Invalid Account Number !");
                                                                                database.loan.c.rollback();
                                                                                
                                                                            } catch (SQLException ex) {
                                                                                bb.setText("**Error in Loan ACCOUNT CREATION !  Try With Another Loan Account Number .");
                                                                            }

                                                                            }
                                                                            else{
                                                                                    bb.setText("Please fill All the details !");
                                                                            }
                                                        /*}
                                                        else
                                                        bb.setText("Loan Account Already Exists ! Try New . ");
                                                        }
                                                        else{
                                                        bb.setText("**");
                                                        }
                                                        } catch (Exception ex) {
                                                        bb.setText("**Error While Communicating To Database !");
                                                        }*/
                                                            
            }catch(Exception e){
                bb.setText(""+e);
                //bb.setText("Please fill ALL the Details Correctly !");
            }
                                                        
        }else{
            bb.setText("Please fill Account Number First !");
        
        }
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noiKeyTyped
        
        
    }//GEN-LAST:event_noiKeyTyped

    private void interKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interKeyTyped
        
    }//GEN-LAST:event_interKeyTyped

    private void lamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamKeyTyped
        
    }//GEN-LAST:event_lamKeyTyped

    private void lamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamKeyReleased

    }//GEN-LAST:event_lamKeyReleased

    private void noiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noiKeyReleased
                    
        if(!lam.getText().equals("")){
        if(!noi.getText().equals("")){
        try{
        
                int NUMBER_OF_INSTALLMENT = Integer.parseInt(noi.getText());

                if(NUMBER_OF_INSTALLMENT !=0 ){

                        int LOAN_AMOUNT =  Integer.parseInt(lam.getText());
                        
                        float INTEREST = Float.parseFloat(inter.getText());
                        
                        float per=( LOAN_AMOUNT * INTEREST ) / 100 ;

                        float TOTAL_AMOUNT = LOAN_AMOUNT+per;

                        float MONTHLY_INSTALMENT =TOTAL_AMOUNT / NUMBER_OF_INSTALLMENT ;
                        
                        mi.setText(String.valueOf(MONTHLY_INSTALMENT));
                        
                        ta.setText(String.valueOf(TOTAL_AMOUNT));

                }else{
                bb.setText("**please fill Valid Number of Installment !");
                }
        }
        catch(Exception e){
          bb.setText("**please fill Amount And Number of Installment In Number Format!");
        }
        
        }
        else
        bb.setText("**please fill Number of Installment !");
        }
        else{
        bb.setText("**please fill Loan Amount !");
        }
        
    }//GEN-LAST:event_noiKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       String s3= an.getText();
        if(!s3.equals("")){
                
            try {
                ResultSet rs=database.loan.st.executeQuery("select account_number from customer_accounts where account_number = '"+s3+"' ");
                    if(rs.next()){
                        long ACCOUNT_NUMBER = Long.parseLong(s3);
                        long vv=rs.getLong(1);
                        
                                if(vv == ACCOUNT_NUMBER){
                                    bb.setText("**"+ACCOUNT_NUMBER+" is Availabe !" );
                                }
                } else
                                     bb.setText("**"+s3+" is Unavailabe !");
            } catch (Exception ex) {
               bb.setText("**Error While Communicating To Database !");
            }
        }else{
            bb.setText("**Please provide the Account Number !");
            an.requestFocusInWindow();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s3= fmdl.getText();
        if(!s3.equals("")){
                
            try {
                ResultSet rs=database.loan.st.executeQuery("select account_number from customer_accounts where account_number = '"+s3+"' ");
                    if(rs.next()){
                        long FMDL = Long.parseLong(fmdl.getText());
                        long vv=rs.getLong(1);
                        
                                if(vv == FMDL){
                                    bb.setText("**"+FMDL+" is Availabe !" );
                                }
                               
                } else
                                     bb.setText("**"+s3+" is Unavailabe !");
            } catch (Exception ex) {
               bb.setText("**Error While Communicating To Database !");
            }
        }else{
            bb.setText("**Please provide the FMDL Account Number !");
            fmdl.requestFocusInWindow();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void anMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_anMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void fmdlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmdlMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_fmdlMouseClicked

    private void comMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_comMouseClicked

    private void salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_salMouseClicked

    private void typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_typeMouseClicked

    private void lamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_lamMouseClicked

    private void noiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noiMouseClicked
        bb.setText(null);
    }//GEN-LAST:event_noiMouseClicked

    private void fmdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmdlActionPerformed
                String s3= fmdl.getText();
        if(!s3.equals("")){
                
            try {
                ResultSet rs=database.loan.st.executeQuery("select account_number from customer_accounts where account_number = '"+s3+"' ");
                    if(rs.next()){
                        long FMDL = Long.parseLong(fmdl.getText());
                        long vv=rs.getLong(1);
                        
                                if(vv == FMDL){
                                    bb.setText("**"+FMDL+" is Availabe !" );
                                }
                               
                } else
                                     bb.setText("**"+s3+" is Unavailabe !");
            } catch (Exception ex) {
               bb.setText("**Error While Communicating To Database !");
            }
        }else{
            bb.setText("**Please provide the FMDL Account Number !");
            fmdl.requestFocusInWindow();
        }
    }//GEN-LAST:event_fmdlActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        an.setText("");
        cd.setDate(null);
        lan.setText("");
        fmdl.setText("");
        com.setText("");
        sal.setText("");
        lam.setText("");
        noi.setText("");
        bb.setText("");
        ta.setText("");
        mi.setText("");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//if(!lan.getText().equals("")){
        if(!an.getText().equals("")){
                    long dd=Long.parseLong(an.getText());
                    String fff="00"+dd+"01";
                    long fsdf=Long.parseLong(fff);
                    lan.setText(String.valueOf(fsdf));
        }else{
                bb.setText("Please Provide The Account Number First!");
                an.requestFocusInWindow();
        }
        /*}else{
        bb.setText("Please Provide The LAN!");
        lan.requestFocusInWindow();
        }*/

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newLoanAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newLoanAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newLoanAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newLoanAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newLoanAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField an;
    private javax.swing.JLabel bb;
    private com.toedter.calendar.JDateChooser cd;
    private javax.swing.JTextField com;
    private javax.swing.JTextField fmdl;
    private javax.swing.JLabel inter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lam;
    private javax.swing.JTextField lan;
    private javax.swing.JLabel mi;
    private javax.swing.JTextField noi;
    private javax.swing.JTextField sal;
    private javax.swing.JLabel ta;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
