/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coding;

import static database.dbconnect.updateUser;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ABHISHEK 
 */
public class UpdateAccount extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAccount
     */
    public UpdateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phnum = new javax.swing.JTextField();
        adda = new javax.swing.JTextField();
        dofb = new com.toedter.calendar.JDateChooser();
        na = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        adr = new javax.swing.JTextArea();
        sta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        g2 = new javax.swing.JRadioButton();
        g1 = new javax.swing.JRadioButton();
        g3 = new javax.swing.JRadioButton();
        m2 = new javax.swing.JRadioButton();
        m1 = new javax.swing.JRadioButton();
        mname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        acn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        occu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nmme = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cunty = new javax.swing.JComboBox<>();
        gggg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Account");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE ACCOUNT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*NAME :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*GENDER :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("*DATE OF BIRTH :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("*PHONE NUMBER :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("*ADDRESS :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("*STATE :");

        phnum.setBackground(new java.awt.Color(204, 255, 204));
        phnum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phnum.setForeground(new java.awt.Color(0, 0, 255));
        phnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phnumMouseClicked(evt);
            }
        });
        phnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnumActionPerformed(evt);
            }
        });

        adda.setBackground(new java.awt.Color(204, 255, 204));
        adda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adda.setForeground(new java.awt.Color(0, 0, 255));
        adda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addaMouseClicked(evt);
            }
        });
        adda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaActionPerformed(evt);
            }
        });

        dofb.setBackground(new java.awt.Color(204, 255, 204));
        dofb.setForeground(new java.awt.Color(0, 0, 255));
        dofb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        na.setBackground(new java.awt.Color(204, 255, 204));
        na.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        na.setForeground(new java.awt.Color(0, 0, 255));
        na.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naMouseClicked(evt);
            }
        });
        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });

        adr.setBackground(new java.awt.Color(204, 255, 204));
        adr.setColumns(20);
        adr.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        adr.setForeground(new java.awt.Color(0, 0, 255));
        adr.setRows(5);
        adr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adr);

        sta.setBackground(new java.awt.Color(204, 255, 204));
        sta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sta.setForeground(new java.awt.Color(0, 0, 255));
        sta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staMouseClicked(evt);
            }
        });
        sta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("*ACCOUNT NUMBER :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("*MARITAL STATUS :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("*MOTHER NAME :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("*FATHER NAME :");

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("UPDATE ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g2);
        g2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        g2.setText("FEMALE");
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g1);
        g1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        g1.setText("MALE");
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(g3);
        g3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        g3.setText("OTHERS");
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(m2);
        m2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        m2.setText("UNMARRIED");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(m1);
        m1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        m1.setText("MARRIED");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        mname.setBackground(new java.awt.Color(204, 255, 204));
        mname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mname.setForeground(new java.awt.Color(0, 0, 255));
        mname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnameMouseClicked(evt);
            }
        });

        fname.setBackground(new java.awt.Color(204, 255, 204));
        fname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 255));
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnameMouseClicked(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("*AADHAR NUMBER :");

        acn.setBackground(new java.awt.Color(204, 255, 204));
        acn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        acn.setForeground(new java.awt.Color(0, 0, 255));
        acn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acnMouseClicked(evt);
            }
        });
        acn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("*OCCUPATION :");

        occu.setBackground(new java.awt.Color(204, 255, 204));
        occu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        occu.setForeground(new java.awt.Color(0, 0, 255));
        occu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                occuMouseClicked(evt);
            }
        });
        occu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occuActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("*NOMINEE :");

        nmme.setBackground(new java.awt.Color(204, 255, 204));
        nmme.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nmme.setForeground(new java.awt.Color(0, 0, 255));
        nmme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmmeMouseClicked(evt);
            }
        });
        nmme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmmeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("GET DETAILS");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("*COUNTRY :");

        cunty.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        cunty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "CHINA", "JAPAN", "AMERICA", "SOUTH AFRICA", "SRI LANKA", "ENGLAND", "AUSTRALIA", "NEPAL" }));
        cunty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuntyMouseClicked(evt);
            }
        });

        gggg.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        gggg.setForeground(new java.awt.Color(255, 51, 0));
        gggg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gggg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dofb, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phnum, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sta, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cunty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(occu, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(g2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(g3))
                                    .addComponent(adda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(m1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmme, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(477, 477, 477)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel5, jLabel6, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cunty, sta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gggg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(g1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(occu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g2)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dofb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phnum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m1)
                            .addComponent(m2)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cunty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 142, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {acn, na, nmme});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnumActionPerformed

    private void addaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addaActionPerformed

    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed

    private void staActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int r=JOptionPane.showConfirmDialog(this, "UPDATE ACCOUNT ?", "UPDATION Conformation !", JOptionPane.YES_NO_OPTION);
        if(r == JOptionPane.YES_OPTION){
                try{
                String NAME=na.getText();

                java.util.Date DT=dofb.getDate();

                long PHONE_NUMBER=Long.parseLong(phnum.getText());
                String ADDRESS =adr.getText();
                String STATE=sta.getText();

                String COUNTRY=(String)cunty.getSelectedItem();

                String OCCUPATION=occu.getText();
                long AADHAR_NUMBER =Long.parseLong(adda.getText());

                String GENDER="";
                    if(g1.isSelected()){
                        GENDER = g1.getText();
                    }
                    else if(g2.isSelected()){
                        GENDER = g2.getText();
                    }
                    else
                        GENDER = g3.getText();



                    String MARITAL_STATUS ="";
                    if(m1.isSelected()){
                        MARITAL_STATUS = m1.getText();
                    }
                    else{
                        MARITAL_STATUS = m2.getText();
                    }
                            
                String MOTHER_NAME =mname.getText();
                String FATHER_NAME =fname.getText();
                String NOMINEE =nmme.getText();

                                if(!acn.getText().equals("") &&  !NAME.equals("") && dofb.getDate() !=null && !phnum.getText().equals("")
                                        && !ADDRESS.equals("") && !STATE.equals("") && !COUNTRY.equals("")
                                        && !OCCUPATION.equals("") &&!adda.getText().equals("") && !GENDER.equals("")
                                        && !MARITAL_STATUS.equals("") && !MOTHER_NAME.equals("")
                                        && !FATHER_NAME.equals("") && !NOMINEE.equals(""))
                                {               //code to convert java.util.Date to java.sql.Date
                                    
                                                                java.sql.Date SQL_BIRTH_DATE = new java.sql.Date(DT.getTime());
                                            try{
                                                         long ACCOUNT_NUM=Long.parseLong(acn.getText());
                                                         
                                                        database.dbconnect.updateUser.setString(1, NAME);
                                                        database.dbconnect.updateUser.setDate(2, SQL_BIRTH_DATE);
                                                        database.dbconnect.updateUser.setLong(3, PHONE_NUMBER);
                                                        database.dbconnect.updateUser.setString(4, ADDRESS);
                                                        database.dbconnect.updateUser.setString(5, STATE);
                                                        database.dbconnect.updateUser.setString(6, COUNTRY);
                                                        database.dbconnect.updateUser.setString(7, OCCUPATION);
                                                        database.dbconnect.updateUser.setLong(8, AADHAR_NUMBER);
                                                        database.dbconnect.updateUser.setString(9, GENDER);
                                                        database.dbconnect.updateUser.setString(10, MARITAL_STATUS);
                                                        database.dbconnect.updateUser.setString(11, MOTHER_NAME);
                                                        database.dbconnect.updateUser.setString(12, FATHER_NAME);
                                                        database.dbconnect.updateUser.setString(13, NOMINEE);
                                                        
                                                        database.dbconnect.updateUser.setLong(14, ACCOUNT_NUM);
                                                        
                                                        int v=database.dbconnect.updateUser.executeUpdate();
                                                            if(v !=0){
                                                                    JOptionPane.showMessageDialog(null,"Account Succesfully Updated !");
                                                                    dispose();
                                                            }
                                                            else{
                                                                    gggg.setText("Error in Updation !  check your Account number.");
                                                            }
                                                      
                                            }catch(Exception e){
                                                gggg.setText("Error While Communicating To Database !!");
                                            }
                                }
                                else{
                                    
                                            gggg.setText("PLEASE FILL UP ALL DETAILS CORRECTLY !!");
                                }

                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        }
        else{
                    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g2ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g1ActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g3ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void occuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(!acn.getText().equals("")){
        try{
                long ACCU=Long.parseLong(acn.getText());
                database.dbconnect.getUser.setLong(1, ACCU);
                ResultSet rs=database.dbconnect.getUser.executeQuery();
                 
                if(rs.next()){
                        
                    na.setText(rs.getString(3));
                    dofb.setDate(rs.getDate(4));
                    phnum.setText(rs.getString(5));
                    adr.setText(rs.getString(6));
                    sta.setText(rs.getString(7));
                    cunty.setSelectedItem(rs.getString(8));
                    occu.setText(rs.getString(9));
                    adda.setText(rs.getString(10));
                        if(rs.getString(11).equals("MALE")){
                                g1.setSelected(true);
                        }
                        else if(rs.getString(11).equals("FEMALE")){
                                g2.setSelected(true);
                        }
                        else
                                g3.setSelected(true);
                        
                                        if(rs.getString(12).equals("MARRIED")){
                                                m1.setSelected(true);
                                         }
                                        else
                                        m2.setSelected(true);
                                    
                    mname.setText(rs.getString(13));
                    fname.setText(rs.getString(14));
                    nmme.setText(rs.getString(16));
                    
                    
                
                }else{
                        gggg.setText("Invalid Account Number !");
                        na.setText("");
                    dofb.setDate(null);
                    phnum.setText("");
                    adr.setText("");
                    sta.setText("");
                    cunty.setSelectedItem("");
                    occu.setText("");
                    adda.setText("");
                        
                                g1.setSelected(false);
                                g2.setSelected(false);
                                g3.setSelected(false);
                        
                                                m1.setSelected(false);
                                                m2.setSelected(false);
                                    
                    mname.setText("");
                    fname.setText("");
                    nmme.setText("");
                }
                
                
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
        }
       }else{
                gggg.setText("Please Provide the Account Number First!");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnActionPerformed
      if(!acn.getText().equals("")){
        try{
                long ACCU=Long.parseLong(acn.getText());
                database.dbconnect.getUser.setLong(1, ACCU);
                ResultSet rs=database.dbconnect.getUser.executeQuery();
                 
                if(rs.next()){
                        
                    na.setText(rs.getString(3));
                    dofb.setDate(rs.getDate(4));
                    phnum.setText(rs.getString(5));
                    adr.setText(rs.getString(6));
                    sta.setText(rs.getString(7));
                    cunty.setSelectedItem(rs.getString(8));
                    occu.setText(rs.getString(9));
                    adda.setText(rs.getString(10));
                        if(rs.getString(11).equals("MALE")){
                                g1.setSelected(true);
                        }
                        else if(rs.getString(11).equals("FEMALE")){
                                g2.setSelected(true);
                        }
                        else
                                g3.setSelected(true);
                        
                                        if(rs.getString(12).equals("MARRIED")){
                                                m1.setSelected(true);
                                         }
                                        else
                                        m2.setSelected(true);
                                    
                    mname.setText(rs.getString(13));
                    fname.setText(rs.getString(14));
                    nmme.setText(rs.getString(16));
                    
                    
                
                }else{
                        gggg.setText("Invalid Account Number !");
                        na.setText("");
                    dofb.setDate(null);
                    phnum.setText("");
                    adr.setText("");
                    sta.setText("");
                    cunty.setSelectedItem("");
                    occu.setText("");
                    adda.setText("");
                        
                                g1.setSelected(false);
                                g2.setSelected(false);
                                g3.setSelected(false);
                        
                                                m1.setSelected(false);
                                                m2.setSelected(false);
                                    
                    mname.setText("");
                    fname.setText("");
                    nmme.setText("");
                }
                
                
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
        }
       }else{
                gggg.setText("Please Provide the Account Number First!");
       }
    }//GEN-LAST:event_acnActionPerformed

    private void nmmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmmeActionPerformed

    private void acnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acnMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_acnMouseClicked

    private void naMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_naMouseClicked

    private void phnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phnumMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_phnumMouseClicked

    private void adrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adrMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_adrMouseClicked

    private void staMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_staMouseClicked

    private void cuntyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuntyMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_cuntyMouseClicked

    private void occuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_occuMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_occuMouseClicked

    private void addaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addaMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_addaMouseClicked

    private void mnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnameMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_mnameMouseClicked

    private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_fnameMouseClicked

    private void nmmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmmeMouseClicked
        gggg.setText(null);
    }//GEN-LAST:event_nmmeMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acn;
    private javax.swing.JTextField adda;
    private javax.swing.JTextArea adr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cunty;
    private com.toedter.calendar.JDateChooser dofb;
    private javax.swing.JTextField fname;
    private javax.swing.JRadioButton g1;
    private javax.swing.JRadioButton g2;
    private javax.swing.JRadioButton g3;
    private javax.swing.JLabel gggg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField na;
    private javax.swing.JTextField nmme;
    private javax.swing.JTextField occu;
    private javax.swing.JTextField phnum;
    private javax.swing.JTextField sta;
    // End of variables declaration//GEN-END:variables
}
